### ISSUE TITLE
Error running software

### ISSUE THREAD

**Issue by d0ubl3puls4r** [fnk0c/cangibrina#5]
Hello, when running the software you have the following error:

Server status: Online (200)
 [+] Testing...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./cangibrina.py", line 147, in start
    self.ItsTime()
  File "./cangibrina.py", line 118, in ItsTime
    HTTPcode = conn.HTTPcode()
  File "src/connection.py", line 99, in HTTPcode
    resp = u.urlopen(self.target).getcode()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: None/acceso.asp

How to solve this problem?

**Comment by fnk0c** [comment]
Hi!

Thank you for posting.
What's the exact command line you're typing? This way I can try to reproduce the error.

**Comment by fnk0c** [comment]
Good news, @d0ubl3puls4r ! 

I found the error. The commit https://github.com/fnk0c/cangibrina/commit/3dfe41654c53fb4a4c9b025f1799dbd244154eef should fix it.

Please, update cangibrina and try again.

Thanks!

**Comment by fnk0c** [comment]
I'll assume that it is fixed. If not, please notify me and I will reopen it
